version: '3.8'
services:
  elasticsearch-node1:
    container_name: elasticsearch-node1
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    networks:
      - elasticsearch-network
    environment:
      - node.name=es-node1
      - cluster.name=es-cluster
      - node.roles=master,data
      - discovery.seed_hosts=elasticsearch-node1, elasticsearch-node2, elasticsearch-node3
      - cluster.initial_master_nodes=es-node1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=_site_

    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"

  elasticsearch-node2:
    container_name: elasticsearch-node2
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    networks:
      - elasticsearch-network
    environment:
      - node.name=es-node2
      - cluster.name=es-cluster
      - node.roles=data
      - discovery.seed_hosts=elasticsearch-node1, elasticsearch-node2, elasticsearch-node3
      - cluster.initial_master_nodes=es-node1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - network.host=_site_
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9201:9200"
      - "9301:9300"

  elasticsearch-node3:
    container_name: elasticsearch-node3
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    networks:
      - elasticsearch-network
    environment:
      - node.name=es-node3
      - cluster.name=es-cluster
      - node.roles=data
      - discovery.seed_hosts=elasticsearch-node1, elasticsearch-node2, elasticsearch-node3
      - cluster.initial_master_nodes=es-node1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - network.host=_site_
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9202:9200"
      - "9302:9300"

networks:
  elasticsearch-network:
    driver: bridge
