version: '3.8'
services:
  elasticsearch-node1:
    container_name: elasticsearch-node1
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    networks:
      - elasticsearch-network
    environment:
      - node.name=es-node1 # 這個node的名稱
      - cluster.name=es-cluster # 這個cluster的名稱
      - node.roles=master,ingest # 這個node的角色
      # discovery.seed_hosts: 這個cluster的所有node
      - discovery.seed_hosts=elasticsearch-node1, elasticsearch-node1, elasticsearch-node3,elasticsearch-node4
      # cluster.initial_master_nodes: 這個cluster的master node
      # 似乎說只有初次啟動的時候會生效 之後cluster 會自己找出
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3,es-node4
      - xpack.security.enabled=false
      # 似乎跟swap 有關 會引響效能
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - network.host=_site_

    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9201:9200"
      - "9301:9300"

  elasticsearch-node2:
    container_name: elasticsearch-node2
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    networks:
      - elasticsearch-network
    environment:
      - node.name=es-node2
      - cluster.name=es-cluster
      - node.roles=master,data
      - discovery.seed_hosts=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3,elasticsearch-node4
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3,es-node4
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - network.host=_site_
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9202:9200"
      - "9302:9300"

  elasticsearch-node3:
    container_name: elasticsearch-node3
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    networks:
      - elasticsearch-network
    environment:
      - node.name=es-node3
      - cluster.name=es-cluster
      - node.roles=data
      - discovery.seed_hosts=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3,elasticsearch-node4
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3,es-node4
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - network.host=_site_
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9203:9200"
      - "9303:9300"

  elasticsearch-node4:
    container_name: elasticsearch-node4
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    networks:
      - elasticsearch-network
    environment:
      - node.name=es-node4
      - cluster.name=es-cluster
      - node.roles=data,ingest
      - discovery.seed_hosts=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3,elasticsearch-node4
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3,es-node4
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - network.host=_site_
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9203:9200"
      - "9303:9300"

networks:
  elasticsearch-network:
    name: elasticsearch-network
    driver: bridge
