version: '3.8'
networks:
  elasticsearch-network:
    name: elasticsearch-network
    driver: bridge

services:
  # Elasticsearch Exporter（用來讓 Prometheus 監控 Elasticsearch）
  elasticsearch-exporter:
    image: bitnami/elasticsearch-exporter:latest
    container_name: elasticsearch-exporter
    networks:
      - elasticsearch-network
    command:
     - '--es.uri=http://es-nginx:9200'
     - '--es.all' # 開這個才會去掃所有的node, 不然就只會有指定的node的資料
    ports:
      - "9114:9114"
    restart: always

  # Prometheus（負責收集數據）
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - elasticsearch-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - elasticsearch-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    restart: always
